environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
install:
  - "%PYTHON%\\python.exe -m pip install --upgrade pip"
build_script:
  - "%PYTHON%\\python.exe -m pip install ."
test_script:
  - "%PYTHON%\\python.exe -c \"from ligo import segments; print(segments(1, 2) + segments(2, 3))\""
