environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
install:
  - "%PYTHON%\\python.exe -m pip install --upgrade pip"
build_script:
  - "%PYTHON%\\python.exe -m pip install ."
